name: Release

# always build releases (to make sure wheel-building works)
# but only publish to PyPI on tags
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/**"
      - "!.github/workflows/release.yml"
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/**"
      - "!.github/workflows/release.yml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -l dist

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.10.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
